# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 26dbc0dadb8acd5dc65b7671e3d29c47bf3f6e8f6e5508bb64414e40bd7e0cc5113740ee69282fc77941cd5044ec3fc6dd2ef18d6eebc0e16c83b49bca37c893
  mailer_domain: <%= ENV["MAILER_DOMAIN"] %>
  mailer_password: <%= ENV["MAILER_PASSWORD"] %>
  mailer_user_name: <%= ENV["MAILER_USER_NAME"] %>
  mailer_address: <%= ENV["MAILER_ADDRESS"] %>
  mailer_port: <%= ENV["MAILER_PORT"] %>
  mailer_authentication: <%= ENV["MAILER_AUTHENTICATION"] %>

test:
  secret_key_base: 1394a6934a82e1a982d4e458c4c5572a25cd305a9cd35974b61e3126b839924bdb26a5f4cb6ae6107b188ca95673a465d04ea41986d2c594483bb1e18ae0e5f2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mailer_domain: <%= ENV["MAILER_DOMAIN"] %>
  mailer_password: <%= ENV["MAILER_PASSWORD"] %>
  mailer_user_name: <%= ENV["MAILER_USER_NAME"] %>
  mailer_address: <%= ENV["MAILER_ADDRESS"] %>
  mailer_port: <%= ENV["MAILER_PORT"] %>
  mailer_authentication: <%= ENV["MAILER_AUTHENTICATION"] %>